### PR TITLE
Fixed feet/inch conversion.

### PR DESCRIPTION
**Pull request by pkobayashi**

### CODE REVIEW

**Comment by bleckers** [comment]
AHA!

This is a regression bug that crept in at the last minute after changing to integer arithmetic for imperial calcs due to noticeable rounding errors with floats (floats are handled as single precision in Arduino land).

We'll get these changes integrated and a new release shortly. Thank you!

**Review by bleckers — APPROVED** [review]

**Comment by osmanozdemir** [comment]
firstly thank for sharing. Can you share circuit diagram picture with us please ? especially PCF8562- LCD connection

**Comment by bleckers** [comment]
Can do! It'll be up in the repo soon.

**Comment by osmanozdemir** [comment]
thanks a lot, i am waiting :)

24 Oca 2021 Pzr 06:24 tarihinde Blair Wyatt <notifications@github.com> şunu
yazdı:

**Comment by bleckers** [comment]
It's up there now :)

https://github.com/SensorDots/SocialDistancingBadge/raw/master/schematic.png

**Comment by osmanozdemir** [comment]
thanks again :) but i don't understand this number at code.  Why lccMap like this? Actually i will use Vim-878 DP LCD, it has 36 pins(32 frontplane+ 4 backplane ) and i dont know how i  can connettion between LCD an PCF8562. I would be grateful if you help me
screen

**Comment by bleckers** [comment]
They are bit shifts which correspond to the ram filling order of the PCF8562 (see page 17 of the datasheet - https://www.nxp.com/docs/en/data-sheet/PCF8562.pdf). It was more to simplify the code, rather than be readable.

From memory, I actually got this mapping by wiring it all up and testing each individual output of the PCF8562, rather than trying to mess about trying to get the ram filling order correct from the get go.

**Pull request merged**
